version: '3.8'

services:
  postgres:
    image: postgres:15.12-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121203
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lab/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend-api
    depends_on:
      - postgres
    ports:
      - "2003:2003"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

volumes:
  pgdata: