version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121203
      POSTGRES_DB: kmipn_db
    ports:
      - "6543:6543"
    volumes:
      - pgdata:/var/lab/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend-api
    depends_on:
      - postgres
    ports:
      - "2003:2003"
    environment:
      DATABASE_URL: "postgresql://postgres:121203@postgres:6543/kmipn_db"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"

volumes:
  pgdata: